/**
 * Practice vocabulary, decks and per-sign difficulty info.
 *
 * Source of truth for words is vocab.json (67 trained classes; also read by
 * scripts/make_demo_clips.py). UNVERIFIED TRANSLATIONS: every entry with
 * `koreanVerified: false` in vocab.json (36 of 67 - everything except the original 31 practice words) has Korean text
 * that has NOT been reviewed by a native speaker. Treat it as a placeholder.
 */
import vocab from "./vocab.json";
import classAccuracy from "./class_accuracy.json";
import videoManifest from "./video-manifest.json";

export type DeckId =
  | "greetings"
  | "people"
  | "food"
  | "time"
  | "getting-around"
  | "feelings"
  | "learning"
  | "questions";

export interface WordEntry {
  /** Practice word; also the demo-video filename stem (public/videos/<english>_example{1,2}.mp4). */
  english: string;
  korean: string;
  /** Original KSL-77 class id (folder id) - the model's label space. */
  classId: number;
  deck: DeckId;
  /** false = UNVERIFIED translation (see file header). */
  koreanVerified: boolean;
}

export interface Deck {
  id: DeckId;
  label: string;
  description: string;
}

export const DECKS: readonly Deck[] = [
  { id: "greetings", label: "Greetings & manners", description: "Hello, thanks, sorry and polite basics" },
  { id: "people", label: "People & family", description: "Who's who, family and personal details" },
  { id: "food", label: "Food & eating", description: "Meals and eating" },
  { id: "time", label: "Time", description: "Now, yesterday, when and how long" },
  { id: "getting-around", label: "Getting around", description: "Transport, places and directions" },
  { id: "feelings", label: "Feelings & attitudes", description: "How things and people feel" },
  { id: "learning", label: "Study, work & fun", description: "Learning, effort, hobbies and everyday actions" },
  { id: "questions", label: "Questions", description: "Asking what and how many" },
];

export const ALL_WORDS: readonly WordEntry[] = vocab.words as WordEntry[];

/** Words whose two demo clips exist in public/videos (generated by scripts/build-video-manifest.mjs). */
const videoWords = new Set<string>(videoManifest.words);
export const hasDemoVideos = (english: string) => videoWords.has(english);

/** Words offered in practice: trained AND have both demo clips. */
export const AVAILABLE_WORDS: readonly WordEntry[] = ALL_WORDS.filter((w) => hasDemoVideos(w.english));

export type DeckChoice = DeckId | "all";

export function wordsInDeck(choice: DeckChoice): WordEntry[] {
  return AVAILABLE_WORDS.filter((w) => choice === "all" || w.deck === choice);
}

/** Decks that currently have at least one practiceable word, with counts. */
export function availableDecks(): (Deck & { count: number })[] {
  return DECKS.map((d) => ({ ...d, count: wordsInDeck(d.id).length })).filter((d) => d.count > 0);
}

export const isDeckChoice = (v: unknown): v is DeckChoice =>
  v === "all" || DECKS.some((d) => d.id === v);

const byEnglish = new Map(ALL_WORDS.map((w) => [w.english, w]));
const byClassId = new Map(ALL_WORDS.map((w) => [w.classId, w]));

export const wordEntry = (english: string) => byEnglish.get(english);
export const classIdForWord = (english: string): number | undefined => byEnglish.get(english)?.classId;
/** Display word for a class id (used in "That looked like …" messages). */
export const wordForClassId = (classId: number): string => byClassId.get(classId)?.english ?? `sign #${classId}`;

// --- Difficulty ---------------------------------------------------------------

/** Signs whose held-out accuracy (fluent signers, signer-out folds) is below this get a "tricky sign" tag. */
export const TRICKY_ACCURACY_THRESHOLD = 0.7;

type ClassAcc = { accuracy: number | null; n: number };
const accuracyTable = classAccuracy.classes as Record<string, ClassAcc>;

/** Held-out accuracy in [0,1] for a practice word, if known. */
export function heldOutAccuracy(english: string): number | undefined {
  const id = classIdForWord(english);
  const a = id === undefined ? undefined : accuracyTable[String(id)]?.accuracy;
  return a ?? undefined;
}

export function isTricky(english: string): boolean {
  const a = heldOutAccuracy(english);
  return a !== undefined && a < TRICKY_ACCURACY_THRESHOLD;
}

/** Groups of signs the model (and learners) commonly confuse; each gets a "compare with" button. */
export const CONFUSABLE_GROUPS: readonly (readonly string[])[] = [
  ["when", "time", "one hour"],
  ["bus", "subway", "ride", "arrive"],
  ["location", "where"],
  ["success", "finally"],
  ["good", "special"],
  ["receive", "experience"],
];

/** Other words in the same confusable group(s) as `english` that have demo videos. */
export function compareCandidates(english: string): string[] {
  const out: string[] = [];
  for (const g of CONFUSABLE_GROUPS) {
    if (!g.includes(english)) continue;
    for (const w of g) if (w !== english && hasDemoVideos(w) && !out.includes(w)) out.push(w);
  }
  return out;
}
